// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
