plugins:
  - rubocop-rails

AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'lib/templates/**/*'
    - 'app/controllers/concerns/*'
    - 'app/models/concerns/*'
    - 'log/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 200

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30
