inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'lib/templates/**/*'
    - 'app/controllers/concerns/*'
    - 'app/models/concerns/*'
    - 'log/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 200

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive
