version: '3.8'

volumes:
  redis:
  postgres:

services:
  server_app: &server_app
    build: .
    command: bundle exec rails server -b 0.0.0.0
    entrypoint: "./entrypoint.sh"
    volumes:
      - .:/home/www/simple_blog
      - /home/www/simple_blog/vendor/bundle
      - /home/www/simple_blog/public/assets
    tty: true
    stdin_open: true
    restart: on-failure
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: simple_blog
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_DB: "redis://in_memory_store:6379"
      SECRET_KEY_BASE: STUB
      DEVISE_SECRET_KEY: STUB
    depends_on:
      - db
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]

  db:
    image: postgres:10
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_blog
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready --dbname=postgres --host=localhost --username=postgres"]
