default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: simple_blog
    username: postgres
    password: postgres
    host: localhost
    port: 5432
  
  queue:
    <<: *default
    database: simple_blog_queue
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    database: simple_blog_cache
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    database: simple_blog_cable
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: simple_blog_test
    username: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
  
  queue:
    <<: *default
    database: simple_blog_test_queue
    username: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    database: simple_blog_test_cache
    username: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    database: simple_blog_test_cable
    username: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: helpbooost_production
    username: helpbooost
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV.fetch("DB_HOST", "helpbooost-db") %>
    port: 5432

  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate

  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate

  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
